#!/bin/bash
#SBATCH -J myGPU          
#SBATCH -o myGPU%j        
#SBATCH -N 2              
#SBATCH -n 4               
#SBATCH -p gtx     
#SBATCH -t 00:00:20         
#SBATCH -A ECE382V

./inverse.out inputs/randomMatrix_20.txt 20
./inverse.out inputs/randomMatrix_50.txt 50
./inverse.out inputs/randomMatrix_100.txt 100