#!/bin/bash
#SBATCH -J matrix_det           # job name
#SBATCH -o matrix_det%j       # output and error file name (%j expands to jobID)
#SBATCH -N 1              # total number of nodes
#SBATCH -n 4              # total number of cores
#SBATCH -p gtx     # queue (partition) -- normal, development, etc.
#SBATCH -t 24:00:00        # run time (hh:mm:ss) - 20 seconds
#SBATCH -A ECE382V
#SBATCH --mail-user=koryyang@utexas.edu # replace by your email
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
# run parallel determinant calculation
./det.out tests/mat_orthogonal_100.txt
./det.out tests/mat_orthogonal_500.txt
./det.out tests/mat_orthogonal_1000.txt
./det.out tests/mat_orthogonal_2000.txt

# run with sequential algorithm for comparison
./det_seq.out tests/mat_orthogonal_100.txt
./det_seq.out tests/mat_orthogonal_500.txt
./det_seq.out tests/mat_orthogonal_1000.txt
./det_seq.out tests/mat_orthogonal_2000.txt